swagger: '2.0'
info:
  version: 2.0.0
  title: Service Ledger Interface- Alert propagation
  contact:
    name: Andrea Margheri
    email: a.margheri@soton.ac.uk
basePath: /sli/alert
consumes:
  - application/json
produces:
  - application/json
paths:
  /store:
    post:
      description: |
        This endpoint is used to store alerts.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: Body in JSON
          required: true
          schema:
            $ref: '#/definitions/store-body'
      responses:
        '200':
          description: The response body for a successful response.
          schema:
            $ref: '#/definitions/store-response'
        '400':
          description: 'Invalid request, required parameter(s) missing.'
        '401':
          description: >-
            The operation is not allowed (unauthorised access, the token is
            invalid, etc.).
  /read:
    post:
      description: |
        This endpoint is used to retrieve the stored alert using the index.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: Body in JSON
          required: true
          schema:
            $ref: '#/definitions/read-body'
      responses:
        '200':
          description: The response body for a successful response.
          schema:
            $ref: '#/definitions/read-response'
        '400':
          description: 'Invalid request, required parameter(s) missing.'
        '401':
          description: >-
            The operation is not allowed (unauthorised access, the token is
            invalid, etc.).
definitions:
  store-body:
    type: object
    description: HTTP body defining the store operation for the /store endpoint.
    required:
      - requestorID
      - token
      - alertType
      - alertSource
      - alertBody
    properties:
      requestorID:
        type: string
        description: Identifier of the requesting entity.
      token:
        type: string
        description: >-
          A crypto token to validate if the entity is allowed to perform the
          requested operation.
      alertType:
        type: string
        enum:
          - POLICY_VIOLATION_ALERT
          - REQ_RESP_DISCREPANCY_ALERT
          - AUDIT_ALERT
          - SLA_ALERT
        description: >-
          POLICY_VIOLATION_ALERT, created by the PVE, corresponds to an alert
          regarding a policy violation. REQ_RESP_DISCREPANCY_ALERT, created by
          the PVE, corresponds to an alert regarding a discrepancy of an XACML
          request/response. AUDIT_ALERT, created by the FSA, corresponds to an
          alert which is generated after performing offline analysis over the
          access control logs.SLA_ALERT, created by FAM, corresponds to an alert
          which is generated after an SLA violation is detected.
      alertSource:
        type: string
        enum:
          - PVE
          - FSA
        description: Refences the entity which has generated the alert.
      alertBody:
        type: string
        description: Base64 encoded alert.
  read-body:
    type: object
    description: HTTP body defining the read operation for the /read endpoint.
    required:
      - requestorID
      - token
      - index
    properties:
      requestorID:
        type: string
        description: Identifier of the requesting entity.
      token:
        type: string
        description: >-
          A crypto token to validate if the entity is allowed to perform the
          requested operation.
      alertID:
        type: string
        description: ID of the requested data as provided during the store operation.
  store-response:
    type: object
    description: HTTP response for a successful store operation.
    required:
      - alertID
    properties:
      index:
        type: string
        description: Identifier of the stored alert.
  read-response:
    type: object
    description: HTTP response for a successful read operation.
    required:
      - alertID
      - alertType
      - alertSource
      - alertBody
    properties:
      alertID:
        type: string
        description: Identifier of the newly created alert.
      alertType:
        type: string
        enum:
          - POLICY_VIOLATION_ALERT
          - REQ_RESP_DISCREPANCY_ALERT
          - AUDIT_ALERT
          - SLA_ALERT
        description: >-
          POLICY_VIOLATION_ALERT, created by the PVE, corresponds to an alert
          regarding a policy violation. REQ_RESP_DISCREPANCY_ALERT, created by
          the PVE, corresponds to an alert regarding a discrepancy of an XACML
          request/response. AUDIT_ALERT, created by the FSA, corresponds to an
          alert which is generated after performing offline analysis over the
          access control logs.SLA_ALERT, created by FAM, corresponds to an alert
          which is generated after an SLA violation is detected.
      alertSource:
        type: string
        enum:
          - PVE
          - FSA
        description: Refences the entity which has generated the alert.
      alertBOdy:
        type: string
        description: Base64 encoded alert.
