swagger: '2.0'

# Document metadata
info:
  version: "0.1"
  title: REST API specification for the SUNFISH Secure multi-party computation (SMC) service
basePath: /SecureComputationMgmt/v1
schemes: 
  - https
# Paths
paths:
  /requestProcess:
    post:
      description: Initiate a new process request at computation nodes.
      parameters:
        - name: data
          required: true
          in: body
          schema:
            type: object
            properties:
              script_name:
                type: string
                description: SecreC program name
              process_id:
                type: integer
                format: uint64
                description: Randomly generated 64-bit unsigned integer. Same for all three computation nodes.
            required:
              - script_name
              - process_id
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          schema:
            type: object
            properties:
              process_id:
                type: integer
                format: uint64
              server:
                type: integer
                description: Server number
              relay_data:
                $ref: '#/definitions/ArrayOfBytes'
                description: Contains signed relay data from the computation node. This data is relayed to the other computation nodes by the next request.
            required:
              - process_id
              - server
              - relay_data
  /relayedProcessShare:
    post:
      description: Relay signed data obtained by `requestProcess` to other computation nodes.
      parameters:
        - name: data
          required: true
          in: body
          schema:
            type: object
            properties:
              process_id:
                type: integer
                format: uint64
              server:
                type: integer
                description: Server number
              relay_data:
                type: array
                items:
                  $ref: '#/definitions/ArrayOfBytes'
                description: Contains signed relay data from all the other computation nodes.
            required:
              - process_id
              - server
              - relay_data
      responses:
        200:
          description: Successful response
          # Body in empty.
  /startProcess:
    post:
      description: Start the SecreC secure computation process on computation nodes.
      parameters:
        - name: data
          required: true
          in: body
          schema:
            type: object
            properties:
              process_id:
                type: integer
                format: uint64
              server:
                type: integer
                description: Server number
              args:
                description: SecreC program arguments, either public or secret-shared.
                type: object
                additionalProperties:
                  type: object
                  # Swagger does not yet support `oneOf` from JSON Schema draft4
                  description: Either `PlainDataArgument` or `SharedDataArgument`.
            required:
              - process_id
              - server
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              process_id:
                type: integer
                format: uint64
              server:
                type: integer
                description: Server number
              vars:
                description: Values published by the SecreC program.
                type: object
                additionalProperties:
                  type: object
                  # Swagger does not yet support `oneOf` from JSON Schema draft4
                  description: Either `PlainDataArgument` or `SharedDataArgument`.
            required:
              - process_id
              - server

definitions:
  PlainDataType:
    description: Valid data type names
    enum:
      - bool
      - uint8
      - uint16
      - uint32
      - uint64
      - int16
      - int32
      - int64
      - float32
      - float64
      - string
  SharedDataType:
    description: Valid secret-shared data type names
    enum:
      - bool
      - uint8
      - uint16
      - uint32
      - uint64
      - int16
      - int32
      - int64
      - float32
      - float64
      - xor_uint8
      - xor_uint16
      - xor_uint32
      - xor_uint64
  ArrayOfBytes:
    description: Array of integer byte values
    type: array
    items:
      type: integer
      minimum: 0
      maximum: 255
  PlainDataArgument:
    type: object
    properties:
      type:
        $ref: '#/definitions/PlainDataType'
      typesize:
        type: integer
        description: Data type size in bytes.
      value:
        $ref: '#/definitions/ArrayOfBytes'
  SharedDataArgument:
    type: object
    properties:
      pd:
        type: string
      type:
        $ref: '#/definitions/SharedDataType'
      typesize:
        type: integer
      value:
        $ref: '#/definitions/ArrayOfBytes'
