swagger: '2.0'

# Document metadata
info:
  version: "0.1"
  title: REST API specification for the SUNFISH SMC Proxy service
basePath: /SMCProxyMgmt/v1
schemes: 
  - https
# Paths
paths:
  /secretShare:
    post:
      description: Secret share input data
      parameters:
        - name: data
          required: true
          in: body
          schema:
            title: PlainDataObjectCollection
            type: object
            # Simple string to model mapping
            # TODO: Use 'pattern' to limit property names to valid argument names?
            additionalProperties:
              $ref: '#/definitions/PlainDataObject'
            minProperties: 1
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing the response object.
          # Use JSON Schema format
          schema:
            title: SecretSharedDataObjectCollection
            type: object
            additionalProperties:
              $ref: '#/definitions/SharedDataObject'
  /reconstruct:
    post:
      description: Reconstruct data from shares
      parameters:
        - name: data
          required: true
          in: body
          schema:
            title: SecretSharedDataObjectCollection
            type: object
            additionalProperties:
              $ref: '#/definitions/SharedDataObject'
            minProperties: 1
      responses:
        200:
          description: Successful response
          schema:
            title: DataObjectCollection
            type: object
            additionalProperties:
              title: DataObject
              type: object
              properties:
                type:
                  $ref: '#/definitions/PlainDataType'
                value:
                  # TODO: This is actually not an `object`, but a basic type
                  type: object
                  description: Basic type value according to the `type` parameter

definitions:
  PlainDataType:
    description: Valid data type names
    enum:
      - bool
      - uint8
      - uint16
      - uint32
      - uint64
      - int16
      - int32
      - int64
      - float32
      - float64
      - string
  SharedDataType:
    description: Valid secret-shared data type names
    enum:
      - bool
      - uint8
      - uint16
      - uint32
      - uint64
      - int16
      - int32
      - int64
      - float32
      - float64
      - xor_uint8
      - xor_uint16
      - xor_uint32
      - xor_uint64
  ArrayOfBytes:
    description: Array of integer byte values
    type: array
    items:
      type: integer
      minimum: 0
      maximum: 255
  PlainDataObject:
    type: object
    properties:
      type:
        $ref: '#/definitions/PlainDataType'
      value:
        $ref: '#/definitions/ArrayOfBytes'
      shared_pd:
        type: string
      shared_type:
        $ref: '#/definitions/SharedDataType'
  SharedDataObject:
    type: object
    properties:
      pd:
        type: string
      type:
        $ref: '#/definitions/SharedDataType'
      typesize:
        type: integer
      shares:
        type: array
        items:
          $ref: '#/definitions/ArrayOfBytes'
