swagger: '2.0'
info:
  version: 2.1.0
  title: SUNFISH Registry Interface
  contact:
    name: Andrea Margheri
    email: a.margheri@soton.ac.uk
basePath: /ri/

consumes:
  - application/json
produces:
  - application/json


paths:
	/dm/store:	
		$ref: #/paths/dm-path.yaml
	/dm/read:	
		$ref: #/paths/dm-path.yaml
	/dm/update:	
		$ref: #/paths/dm-path.yaml
	/dm/delete:	
		$ref: #/paths/dm-path.yaml

definitions:
	$ref: #/definitions/dm-def.yaml