swagger: '2.0'
info:
  version: 2.1.0
  title: SUNFISH Registry Interface
  contact:
    name: Andrea Margheri
    email: a.margheri@soton.ac.uk
basePath: /ri/

consumes:
  - application/json
produces:
  - application/json

tags:
  - dm
  - policy

paths:
	/dm/store:
	post:
	  description: >
	    Storing encryption/tokenization key
	  consumes:
	    - application/json
	  produces:
	    - application/json
	  parameters:
	    - name: body
	      in: body
	      description: Body in JSON
	      required: true
	      schema:
	        $ref: '../definitions/dm-def.yaml/#dm-store-body'
	  responses:
	    '200':
	      description: The response body for a successful response.
	      schema:
	        $ref: '../definitions/dm-def.yaml/#dm-response'
	    '400':
	      description: 'Invalid request, required parameter(s) missing.'
	    '401':
	      description: >-
	        The operation is not allowed (unauthorised access, the token is
	        invalid, etc.).
		
	/dm/read:
	post:
	  description: |
	    This endpoint is used to retrieve a key.
	  consumes:
	    - application/json
	  produces:
	    - application/json
	  parameters:
	    - name: body
	      in: body
	      description: Body in JSON
	      required: true
	      schema:
	        $ref: '../definitions/dm-def.yaml/#dm-read-body'
	  responses:
	    '200':
	      description: The response body for a successful response.
	      schema:
	        $ref: '../definitions/dm-def.yaml/#dm-read-response'
	    '400':
	      description: 'Invalid request, required parameter(s) missing'
	    '401':
	      description: >-
	        The operation is not allowed (unauthorised access, the token is
	        invalid, etc.).
		
	/dm/update:
	post:
	  description: |
	    This endpoint is used to update a public key given a userID.
	  consumes:
	    - application/json
	  produces:
	    - application/json
	  parameters:
	    - name: body
	      in: body
	      description: Body in JSON
	      required: true
	      schema:
	        $ref: '../definitions/dm-def.yaml/#dm-update-body'
	  responses:
	    '200':
	      description: The response body for a successful response.
	      schema:
	        $ref: '../definitions/dm-def.yaml/#dm-message_response'
	    '400':
	      description: 'Invalid request, required parameter(s) missing.'
	    '401':
	      description: >-
	        The operation is not allowed (unauthorised access, the token is
	        invalid, etc.).
		
	/dm/delete:
	post:
	  description: |
	    This endpoint is used to destroy a key. 
	  consumes:
	    - application/json
	  produces:
	    - application/json
	  parameters:
	    - name: body
	      in: body
	      required: true
	      schema:
	        $ref: '../definitions/dm-def.yaml/#dm-delete-body'
	  responses:
	    '200':
	      description: The response body for a successful response.
	      schema:
	        $ref: '../definitions/dm-def.yaml/#dm-message_response'
	    '400':
	      description: 'Invalid request, required parameter(s) missing'
	    '401':
	      description: >-
	        The operation is not allowed (unauthorised access, the token is
	        invalid, etc.).
	